<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Sistema Ventas (PDO & MYSQL)</title>
		<link rel="stylesheet" href="<?=$assets_css?>bootstrap.min.css">
		<link rel="stylesheet" href="<?=$assets_css?>material-kit.css">
		<link rel="stylesheet" href="<?=$base_url?>public/iconfont/material-icons.css">
		<link rel="stylesheet" href="<?=$assets_css?>custom.css">
	</head>
	<body>